server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb  # In-memory H2 database
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    h2:
      console:
        enabled: true  # Enable H2 console for easy database access
    # In-memory database settings (temporary data for testing, etc.)
  jpa:
    hibernate:
      ddl-auto: update  # Automatically create or update tables
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          facebook:
            client-id: YOUR_FACEBOOK_CLIENT_ID
            client-secret: YOUR_FACEBOOK_CLIENT_SECRET
            scope: public_profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          facebook:
            authorization-uri: https://www.facebook.com/v9.0/dialog/oauth
            token-uri: https://graph.facebook.com/v9.0/oauth/access_token
            user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture

jwt:
  secret: your_jwt_secret_key
  expirationMs: 86400000  # 24 hours in milliseconds

logging:
  level:
    org.springframework.security: DEBUG

# CORS settings (if needed)
spring:
  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET, POST, PUT, DELETE, OPTIONS"
      allowed-headers: "Authorization, Cache-Control, Content-Type"
      allow-credentials: true

# Profile-specific configurations (e.g., dev, prod)
spring:
  profiles:
    active: dev  # or prod, depending on your environment

# Application name or other custom properties
app:
  name: User Access Management
  description: Microservice for user authentication and role-based access control
